### ISSUE TITLE
Update link to API docs

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/tradeoff-analytics-nodejs#43]
Link goes to old swagger http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/apis/#!/tradeoff-analytics

Needs to go to new API explorer:
https://watson-api-explorer.mybluemix.net/apis/tradeoff-analytics-v1

**Comment by germanattanasio** [comment]
PR?

**Comment by SirSpidey** [comment]
@germanattanasio, should have created branch and PR, but just committed to master.

**Comment by germanattanasio** [comment]
commit to master is fine allen :balloon:

**Comment by jzhang300** [comment]
Do we need to PR for small things like link updates?

**Comment by germanattanasio** [comment]
nope that's why I told allen to do a commit
