### ISSUE TITLE
tradeoff-analytics-nodejs

### ISSUE THREAD

**Issue by PaulRead** [watson-developer-cloud/tradeoff-analytics-nodejs#47]
Is there anyway in the new widget to customize the sliders? For example I have one column which currency value  with prices  between 9.99 and 1250.00, I would like to set slider so that shows 0 to 1250 in steps of 50.
I would also like to display the values for the columns even if I am only only selecting 3 out of 6 columns.
Is there a way to view the auto-excluded data?

**Comment by boazdavid** [comment]
This demo is very simple by intention. It focuses on demonstrating the service input and output.
In this demo, there is no way to customize the sliders, or to show the values for columns that are not analyzed.
BTW, this is a [demo ](https://tradeoff-analytics-ui-demo.mybluemix.net) of the new ToA widget. It may provide the functionalities you are looking for.

**Comment by PaulRead** [comment]
I think that this does answer my questions. Can you give me an idea on when this might be available **live**!
