### ISSUE TITLE
UI widget integration issue : ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by purval** [watson-developer-cloud/tradeoff-analytics-nodejs#50]
Hi,
I am trying to integrate sample tradeoff-analytics-nodejs application with our existing nodejs application. It loads the parameter selection step perfectly while calling backend api /tradeoff-analytics-token it gives **ForbiddenError: invalid csrf token**.
I have tried searching the solution but I am not much aware with the csrf token process.
Have faced such errors or can you guide me with the integration?

**Comment by germanattanasio** [comment]
you are probably calling the API without sending the `csrf` token. Either disable it in the `security.js` file or add the `token` to the header.
