### ISSUE TITLE
Question for Watson TA

### ISSUE THREAD

**Issue by asetiyadi** [watson-developer-cloud/tradeoff-analytics-nodejs#7]
Hi .. I have question/comment about the Watson Tradeoff Analytics (GA version):

1.  When the service is created in Bluemix, it generates the `VCAP_SERVICES`.  I notice if runs locally (not using process.env), the "version" is added for credentials however if using process.env it does not, thus the call failed and I have to add "version" manually.  Any reason the "version" is not part of `VCAP_SERVICES` credentials?

2.  What is the pros and cons of pulling down "TradeoffAnalytics.js" locally instead of using the url "https://ta-cdn.mybluemix.net/v1/TradeoffAnalytics.js"?  

3.  Just a note: in an SPA using AngularJS, the embedded mode throws dojo reference error.

Thank you.

**Comment by germanattanasio** [comment]
1. We don't want to automatically assume the api version. See https://github.com/watson-developer-cloud/nodejs-wrapper/issues/40

2. You won't get bug fixing and updates if use that file locally.

3. Can you provide more information on the error you are getting
